# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 71b6c8d6ed939614939921b7236be1fe294c8417d1ae21948cfb78655f3ce9e395f859794dbe240c0c1d3427a04958cc1ee677b3f19f2de6de07c13856593a05

test:
  secret_key_base: 2d92bc92ed03e405226a4163c11d0c99b12ae0548b730c14dc97650e0e6efda596e53cae2329d595eee25fd37ff5401cba58c59f2620235669df342ab0aee348

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
